#!/usr/bin/env python3
# tamanna_command.py
# Tamanna Language System – Sensing & Building

import os
import platform
import sys
from datetime import datetime

BANNER = r"""
████████╗ █████╗ ███╗   ███╗ █████╗ ███╗   ██╗███╗   ██╗ █████╗ 
╚══██╔══╝██╔══██╗████╗ ████║██╔══██╗████╗  ██║████╗  ██║██╔══██╗
   ██║   ███████║██╔████╔██║███████║██╔██╗ ██║██╔██╗ ██║███████║
   ██║   ██╔══██║██║╚██╔╝██║██╔══██║██║╚██╗██║██║╚██╗██║██╔══██║
   ██║   ██║  ██║██║ ╚═╝ ██║██║  ██║██║ ╚████║██║ ╚████║██║  ██║
   ╚═╝   ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═══╝╚═╝  ╚═╝
Tamanna Language System – Sensing & Building
"""

HELP_TEXT = """
Commands:
  help                 Show this help
  sense                Sense system + language sample
  sense text <msg>     Sense language of given text
  build proj <name>    Build a Tamanna project skeleton
  info                 Show system info
  clear                Clear the screen
  exit / quit          Exit Tamanna command

Examples:
  sense
  sense text Amar nam Tamanna
  build proj tamanna_editor
"""

# ---------- LANGUAGE SENSE ----------


def detect_language_simple(text: str) -> str:
    """
    Very simple heuristic:
    - If contains Bengali Unicode range, mark as 'Bangla'
    - Else if mostly ASCII letters, mark as 'English'
    - Else 'Mixed/Unknown'
    """
    bengali_range = range(0x0980, 0x09FF + 1)
    bengali_count = sum(1 for ch in text if ord(ch) in bengali_range)
    ascii_letters = sum(1 for ch in text if ch.isascii() and ch.isalpha())
    total = len(text) or 1

    if bengali_count / total > 0.2:
        return "Bangla (detected by script range)"
    if ascii_letters / total > 0.4:
        return "English (mostly ASCII letters)"
    return "Mixed / Unknown"


# ---------- SYSTEM SENSE ----------


def sense_system():
    print("\n[System Sense]")
    print(f"  Time       : {datetime.now().isoformat(sep=' ', timespec='seconds')}")
    print(f"  OS         : {platform.system()} {platform.release()}")
    print(f"  Machine    : {platform.machine()}")
    print(f"  Python     : {platform.python_version()}")
    print(f"  Executable : {sys.executable}")
    print("")


# ---------- PROJECT BUILD ----------


def build_project(name: str):
    root = os.path.abspath(name)
    if not os.path.exists(root):
        os.makedirs(root)

    src_dir = os.path.join(root, "src")
    os.makedirs(src_dir, exist_ok=True)

    readme_path = os.path.join(root, "README.md")
    main_path = os.path.join(src_dir, "main.py")

    if not os.path.exists(readme_path):
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(f"# {name}\n\n")
            f.write("Tamanna Language System – Project Skeleton\n\n")
            f.write("- Generated by `tamanna_command.py`\n")
            f.write("- Place your core logic in `src/main.py`\n")

    if not os.path.exists(main_path):
        with open(main_path, "w", encoding="utf-8") as f:
            f.write('"""\n')
            f.write(f"{name} – Tamanna module entrypoint\n")
            f.write('"""\n\n')
            f.write("def main():\n")
            f.write("    print('Tamanna module online:', __name__)\n\n")
            f.write("if __name__ == '__main__':\n")
            f.write("    main()\n")

    print(f"\n[Build]")
    print(f"  Project root : {root}")
    print(f"  Created      : README.md, src/main.py (if missing)")
    print("  Status       : Tamanna project skeleton ready.\n")


# ---------- COMMAND LOOP ----------


def handle_command(cmd: str):
    parts = cmd.strip().split()
    if not parts:
        return

    base = parts[0].lower()

    if base in ("exit", "quit"):
        print("Tamanna: closing command loop. Bye.")
        raise SystemExit

    if base == "help":
        print(HELP_TEXT)
        return

    if base == "clear":
        os.system("cls" if os.name == "nt" else "clear")
        return

    if base == "info":
        sense_system()
        return

    if base == "sense":
        if len(parts) >= 3 and parts[1].lower() == "text":
            text = " ".join(parts[2:])
            lang = detect_language_simple(text)
            print(f"\n[Language Sense]")
            print(f"  Text : {text}")
            print(f"  Lang : {lang}\n")
        else:
            sense_system()
            sample = input(
                "Enter sample text to sense language (or leave empty): "
            ).strip()
            if sample:
                lang = detect_language_simple(sample)
                print(f"\n[Language Sense]")
                print(f"  Text : {sample}")
                print(f"  Lang : {lang}\n")
        return

    if base == "build":
        if len(parts) >= 3 and parts[1].lower() == "proj":
            name = parts[2]
            build_project(name)
        else:
            print("Usage: build proj <name>")
        return

    print(f"Unknown command: {cmd}")
    print("Type `help` for available commands.")


def main():
    print(BANNER)
    print("Type `help` to see commands.\n")

    while True:
        try:
            cmd = input("Tamanna> ")
        except (EOFError, KeyboardInterrupt):
            print("\nTamanna: closing command loop. Bye.")
            break

        try:
            handle_command(cmd)
        except SystemExit:
            break
        except Exception as e:
            print(f"[Error] {e}")


if __name__ == "__main__":
    main()
