package com.tamanna.upgrade

import android.content.Context
import java.util.*

class SelfUpgradeManager_010(private val context: Context) {

    private val engine = SelfUpgradeEngine_009(context)
    private val scheduledTasks = mutableListOf<Timer>()

    fun scheduleUpgradeTask(intervalMs: Long = 5000) {
        val timer = Timer()
        timer.scheduleAtFixedRate(object : TimerTask() {
            override fun run() {
                val sampleCode = """
                    package com.tamanna.generated

                    class AutoGenerated {
                        fun hello() = "Hello from AutoGenerated"
                    }
                """.trimIndent()
                val fileName = "AutoGenerated_${System.currentTimeMillis()}.kt"
                engine.createFile(fileName, sampleCode, "kotlin_files")
            }
        }, 0, intervalMs)
        scheduledTasks.add(timer)
    }

    fun stopAllTasks() {
        for (t in scheduledTasks) t.cancel()
        scheduledTasks.clear()
    }
}