name: Auto Clean Repo

on:
  push:
    branches: [ "main" ]

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Auto Cleaner
        run: python auto_clean_repo.py