      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Packages
        run: npm install

      - name: Run All JS Files
        run: |
          find . -type f -name "*.js" -exec node {} \;