name: Auto Sync to Repo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run PowerHub Helper
        run: python bd-king-r7/it/bd-king-r7/powerhub/powerhub_helper/bd-king-r7_powerhub.bad
auto_install.bad
auto_sync.bad
bd-king-r7_ultra_synce.bad
warking_helper.bad